### ISSUE TITLE
index.html page not working

### ISSUE THREAD

**Issue by hoogw** [Esri/3d-viewer#1]
<script type="module" crossorigin="use-credentials"
    src="../node_modules/@esri/calcite-components/dist/calcite/calcite.esm.js">
    </script>
                    <script nomodule="" src="../node_modules/@esri/calcite-components/dist/calcite/calcite.js"></script>

I get 404 error for above 2 line

                     src="../node_modules......

   should be: 

                   src="./node_modules

node_modules and index are at same directory, should use ./node_modules correct?

I modify it, but still not work, because, your package.json does not have calcite-components

**Comment by hoogw** [comment]
after install calcite-components
still not working, since many ../node_modules related path are wrong, not right. 

I did download .zip.   unfold zip.
run 'npm install'

still not working

**Comment by hoogw** [comment]
get error, install following: 

                                    gemini@geminis-iMac esri3d % npm install  @esri/application-base-js
Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at Conf.loadPrefix (/usr/local/lib/node_modules/npm/lib/config/load-prefix.js:46:24)
    at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)
    at Conf.emit (events.js:314:20)
    at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:338:27)
    at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
internal/bootstrap/switches/does_own_process_state.js:129
    cachedCwd = rawMethods.cwd();
                           ^

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:183:30)
    at process.emit (events.js:314:20)
    at process._fatalException (internal/process/execution.js:156:25) {
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}
gemini@geminis-iMac esri3d %

**Comment by hoogw** [comment]
You mean I have to manually install following ?

Application Base ( see error above, failed)
Calcite Componnents ( yes, install ok)
Configurable App Components ( see error above, failed)
Telemetry. ( I see it is already there)

**Comment by hoogw** [comment]
I installed all 4 , all of them are ok, 


Application Base
Calcite Componnents 
Configurable App Components 
Telemetry

But still get error:

           Do I need to run 

           npm install ?  It was not on document.
